echo "------------tags------------";
python3 create_playlist.py -u matteo7moh -f sorted_tracks.csv -s sp yt -Ti acid;
python3 create_playlist.py -u matteo7moh -f sorted_tracks.csv -s sp yt -Ti melodic -Te heavy;
python3 create_playlist.py -u matteo7moh -f sorted_tracks.csv -s sp yt -Ti soft -Te powerful;
python3 create_playlist.py -u matteo7moh -f sorted_tracks.csv -s sp yt -Ti heavy;
python3 create_playlist.py -u matteo7moh -f sorted_tracks.csv -s sp yt -Ti no_beat;
python3 create_playlist.py -u matteo7moh -f sorted_tracks.csv -s sp yt -Ti voice;
python3 create_playlist.py -u matteo7moh -f sorted_tracks.csv -s sp yt -Ti modular; # skipped
echo "------------genres 2------------";
python3 create_playlist.py -u matteo7moh -f sorted_tracks.csv -s sp yt -g rock punk;
python3 create_playlist.py -u matteo7moh -f sorted_tracks.csv -s sp yt -g alternative_rock punk indie alternative;
python3 create_playlist.py -u matteo7moh -f sorted_tracks.csv -s sp yt -g deep_house;
python3 create_playlist.py -u matteo7moh -f sorted_tracks.csv -s sp yt -g house electro_house minimal_house;
python3 create_playlist.py -u matteo7moh -f sorted_tracks.csv -s sp yt -g classical;
python3 create_playlist.py -u matteo7moh -f sorted_tracks.csv -s sp yt -g electronic;
python3 create_playlist.py -u matteo7moh -f sorted_tracks.csv -s sp yt -g contemporary_classical;
python3 create_playlist.py -u matteo7moh -f sorted_tracks.csv -s sp yt -g experimental;
python3 create_playlist.py -u matteo7moh -f sorted_tracks.csv -s sp yt -g ambient;
python3 create_playlist.py -u matteo7moh -f sorted_tracks.csv -s sp yt -g folk;
python3 create_playlist.py -u matteo7moh -f sorted_tracks.csv -s sp yt -g chill_hop;
python3 create_playlist.py -u matteo7moh -f sorted_tracks.csv -s sp yt -g hip_hop;
python3 create_playlist.py -u matteo7moh -f sorted_tracks.csv -s sp yt -g techno;
python3 create_playlist.py -u matteo7moh -f sorted_tracks.csv -s sp yt -g future_bass;
python3 create_playlist.py -u matteo7moh -f sorted_tracks.csv -s sp yt -g pop;
echo "------------genres 3------------";
python3 create_playlist.py -u matteo7moh -f sorted_tracks.csv -s sp yt -g house electro_house minimal_house -r 3;
python3 create_playlist.py -u matteo7moh -f sorted_tracks.csv -s sp yt -g classical -r 3;
python3 create_playlist.py -u matteo7moh -f sorted_tracks.csv -s sp yt -g electronic -r 3;
python3 create_playlist.py -u matteo7moh -f sorted_tracks.csv -s sp yt -g ambient contemporary_classical experimental modern folk minimalism chill_hop -r 3;
python3 create_playlist.py -u matteo7moh -f sorted_tracks.csv -s sp yt -g techno -r 3;
